name: caffeine
favicon: null
layout_spectrum: 0.43222
typography_spectrum: 0.4064
title: Coffee
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7b6a62'
    - '#3f3a37'
    - '#141517'
    - '#dddbce'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
