name: caffeine
favicon: null
layout_spectrum: 0.6813956922851503
typography_spectrum: 0.3375507143791765
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7b6a62'
    - '#3f3a37'
    - '#141517'
    - '#dddbce'
  brandStrength: 0
  lightness: 0.41163552715443075
  saturation: 0.13395180087536573
  rhythmicContrast: 0.8637846510391682
purpose: []
